package com.lioncorp.example.store.proxy.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RevertedDocList.proto

public final class RevertedDocListOuterClass {
  private RevertedDocListOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RevertedDocListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RevertedDocList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
     */
    java.util.List<RevertedDocList.DocItem>
        getDocItemList();
    /**
     * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
     */
    RevertedDocList.DocItem getDocItem(int index);
    /**
     * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
     */
    int getDocItemCount();
    /**
     * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
     */
    java.util.List<? extends RevertedDocList.DocItemOrBuilder>
        getDocItemOrBuilderList();
    /**
     * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
     */
    RevertedDocList.DocItemOrBuilder getDocItemOrBuilder(
            int index);

    /**
     * <code>required string type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 2;</code>
     */
    String getType();
    /**
     * <code>required string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code RevertedDocList}
   */
  public  static final class RevertedDocList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RevertedDocList)
      RevertedDocListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RevertedDocList.newBuilder() to construct.
    private RevertedDocList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RevertedDocList() {
      docItem_ = java.util.Collections.emptyList();
      type_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RevertedDocList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                docItem_ = new java.util.ArrayList<DocItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              docItem_.add(
                  input.readMessage(DocItem.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              type_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          docItem_ = java.util.Collections.unmodifiableList(docItem_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RevertedDocListOuterClass.internal_static_RevertedDocList_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RevertedDocListOuterClass.internal_static_RevertedDocList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RevertedDocList.class, Builder.class);
    }

    public interface DocItemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:RevertedDocList.DocItem)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string docId = 1;</code>
       */
      boolean hasDocId();
      /**
       * <code>required string docId = 1;</code>
       */
      String getDocId();
      /**
       * <code>required string docId = 1;</code>
       */
      com.google.protobuf.ByteString
          getDocIdBytes();

      /**
       * <code>optional float score = 2;</code>
       */
      boolean hasScore();
      /**
       * <code>optional float score = 2;</code>
       */
      float getScore();

      /**
       * <code>optional string reason = 3;</code>
       */
      boolean hasReason();
      /**
       * <code>optional string reason = 3;</code>
       */
      String getReason();
      /**
       * <code>optional string reason = 3;</code>
       */
      com.google.protobuf.ByteString
          getReasonBytes();
    }
    /**
     * Protobuf type {@code RevertedDocList.DocItem}
     */
    public  static final class DocItem extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:RevertedDocList.DocItem)
        DocItemOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use DocItem.newBuilder() to construct.
      private DocItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private DocItem() {
        docId_ = "";
        score_ = 0F;
        reason_ = "";
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private DocItem(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                docId_ = bs;
                break;
              }
              case 21: {
                bitField0_ |= 0x00000002;
                score_ = input.readFloat();
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                reason_ = bs;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RevertedDocListOuterClass.internal_static_RevertedDocList_DocItem_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RevertedDocListOuterClass.internal_static_RevertedDocList_DocItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DocItem.class, Builder.class);
      }

      private int bitField0_;
      public static final int DOCID_FIELD_NUMBER = 1;
      private volatile Object docId_;
      /**
       * <code>required string docId = 1;</code>
       */
      public boolean hasDocId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string docId = 1;</code>
       */
      public String getDocId() {
        Object ref = docId_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            docId_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string docId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDocIdBytes() {
        Object ref = docId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          docId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SCORE_FIELD_NUMBER = 2;
      private float score_;
      /**
       * <code>optional float score = 2;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional float score = 2;</code>
       */
      public float getScore() {
        return score_;
      }

      public static final int REASON_FIELD_NUMBER = 3;
      private volatile Object reason_;
      /**
       * <code>optional string reason = 3;</code>
       */
      public boolean hasReason() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string reason = 3;</code>
       */
      public String getReason() {
        Object ref = reason_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            reason_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string reason = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasDocId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, docId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeFloat(2, score_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reason_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, docId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, score_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, reason_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof DocItem)) {
          return super.equals(obj);
        }
        DocItem other = (DocItem) obj;

        boolean result = true;
        result = result && (hasDocId() == other.hasDocId());
        if (hasDocId()) {
          result = result && getDocId()
              .equals(other.getDocId());
        }
        result = result && (hasScore() == other.hasScore());
        if (hasScore()) {
          result = result && (
              Float.floatToIntBits(getScore())
              == Float.floatToIntBits(
                  other.getScore()));
        }
        result = result && (hasReason() == other.hasReason());
        if (hasReason()) {
          result = result && getReason()
              .equals(other.getReason());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasDocId()) {
          hash = (37 * hash) + DOCID_FIELD_NUMBER;
          hash = (53 * hash) + getDocId().hashCode();
        }
        if (hasScore()) {
          hash = (37 * hash) + SCORE_FIELD_NUMBER;
          hash = (53 * hash) + Float.floatToIntBits(
              getScore());
        }
        if (hasReason()) {
          hash = (37 * hash) + REASON_FIELD_NUMBER;
          hash = (53 * hash) + getReason().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static DocItem parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DocItem parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DocItem parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DocItem parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DocItem parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DocItem parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DocItem parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static DocItem parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static DocItem parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static DocItem parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static DocItem parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static DocItem parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(DocItem prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code RevertedDocList.DocItem}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:RevertedDocList.DocItem)
          DocItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return RevertedDocListOuterClass.internal_static_RevertedDocList_DocItem_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return RevertedDocListOuterClass.internal_static_RevertedDocList_DocItem_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  DocItem.class, Builder.class);
        }

        // Construct using RevertedDocListOuterClass.RevertedDocList.DocItem.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          docId_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          score_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000002);
          reason_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return RevertedDocListOuterClass.internal_static_RevertedDocList_DocItem_descriptor;
        }

        @Override
        public DocItem getDefaultInstanceForType() {
          return DocItem.getDefaultInstance();
        }

        @Override
        public DocItem build() {
          DocItem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public DocItem buildPartial() {
          DocItem result = new DocItem(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.docId_ = docId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.score_ = score_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.reason_ = reason_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof DocItem) {
            return mergeFrom((DocItem)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(DocItem other) {
          if (other == DocItem.getDefaultInstance()) return this;
          if (other.hasDocId()) {
            bitField0_ |= 0x00000001;
            docId_ = other.docId_;
            onChanged();
          }
          if (other.hasScore()) {
            setScore(other.getScore());
          }
          if (other.hasReason()) {
            bitField0_ |= 0x00000004;
            reason_ = other.reason_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          if (!hasDocId()) {
            return false;
          }
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          DocItem parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (DocItem) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private Object docId_ = "";
        /**
         * <code>required string docId = 1;</code>
         */
        public boolean hasDocId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string docId = 1;</code>
         */
        public String getDocId() {
          Object ref = docId_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              docId_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string docId = 1;</code>
         */
        public com.google.protobuf.ByteString
            getDocIdBytes() {
          Object ref = docId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            docId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string docId = 1;</code>
         */
        public Builder setDocId(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          docId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string docId = 1;</code>
         */
        public Builder clearDocId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          docId_ = getDefaultInstance().getDocId();
          onChanged();
          return this;
        }
        /**
         * <code>required string docId = 1;</code>
         */
        public Builder setDocIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          docId_ = value;
          onChanged();
          return this;
        }

        private float score_ ;
        /**
         * <code>optional float score = 2;</code>
         */
        public boolean hasScore() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional float score = 2;</code>
         */
        public float getScore() {
          return score_;
        }
        /**
         * <code>optional float score = 2;</code>
         */
        public Builder setScore(float value) {
          bitField0_ |= 0x00000002;
          score_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float score = 2;</code>
         */
        public Builder clearScore() {
          bitField0_ = (bitField0_ & ~0x00000002);
          score_ = 0F;
          onChanged();
          return this;
        }

        private Object reason_ = "";
        /**
         * <code>optional string reason = 3;</code>
         */
        public boolean hasReason() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string reason = 3;</code>
         */
        public String getReason() {
          Object ref = reason_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              reason_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string reason = 3;</code>
         */
        public com.google.protobuf.ByteString
            getReasonBytes() {
          Object ref = reason_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            reason_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string reason = 3;</code>
         */
        public Builder setReason(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          reason_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string reason = 3;</code>
         */
        public Builder clearReason() {
          bitField0_ = (bitField0_ & ~0x00000004);
          reason_ = getDefaultInstance().getReason();
          onChanged();
          return this;
        }
        /**
         * <code>optional string reason = 3;</code>
         */
        public Builder setReasonBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          reason_ = value;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:RevertedDocList.DocItem)
      }

      // @@protoc_insertion_point(class_scope:RevertedDocList.DocItem)
      private static final DocItem DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new DocItem();
      }

      public static DocItem getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @Deprecated public static final com.google.protobuf.Parser<DocItem>
          PARSER = new com.google.protobuf.AbstractParser<DocItem>() {
        @Override
        public DocItem parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DocItem(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<DocItem> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<DocItem> getParserForType() {
        return PARSER;
      }

      @Override
      public DocItem getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int DOCITEM_FIELD_NUMBER = 1;
    private java.util.List<DocItem> docItem_;
    /**
     * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
     */
    public java.util.List<DocItem> getDocItemList() {
      return docItem_;
    }
    /**
     * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
     */
    public java.util.List<? extends DocItemOrBuilder>
        getDocItemOrBuilderList() {
      return docItem_;
    }
    /**
     * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
     */
    public int getDocItemCount() {
      return docItem_.size();
    }
    /**
     * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
     */
    public DocItem getDocItem(int index) {
      return docItem_.get(index);
    }
    /**
     * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
     */
    public DocItemOrBuilder getDocItemOrBuilder(
        int index) {
      return docItem_.get(index);
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile Object type_;
    /**
     * <code>required string type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string type = 2;</code>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDocItemCount(); i++) {
        if (!getDocItem(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < docItem_.size(); i++) {
        output.writeMessage(1, docItem_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < docItem_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, docItem_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RevertedDocList)) {
        return super.equals(obj);
      }
      RevertedDocList other = (RevertedDocList) obj;

      boolean result = true;
      result = result && getDocItemList()
          .equals(other.getDocItemList());
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && getType()
            .equals(other.getType());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDocItemCount() > 0) {
        hash = (37 * hash) + DOCITEM_FIELD_NUMBER;
        hash = (53 * hash) + getDocItemList().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RevertedDocList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RevertedDocList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RevertedDocList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RevertedDocList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RevertedDocList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RevertedDocList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RevertedDocList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RevertedDocList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RevertedDocList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RevertedDocList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RevertedDocList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RevertedDocList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RevertedDocList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RevertedDocList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RevertedDocList)
        RevertedDocListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RevertedDocListOuterClass.internal_static_RevertedDocList_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RevertedDocListOuterClass.internal_static_RevertedDocList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RevertedDocList.class, Builder.class);
      }

      // Construct using RevertedDocListOuterClass.RevertedDocList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDocItemFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (docItemBuilder_ == null) {
          docItem_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          docItemBuilder_.clear();
        }
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RevertedDocListOuterClass.internal_static_RevertedDocList_descriptor;
      }

      @Override
      public RevertedDocList getDefaultInstanceForType() {
        return RevertedDocList.getDefaultInstance();
      }

      @Override
      public RevertedDocList build() {
        RevertedDocList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RevertedDocList buildPartial() {
        RevertedDocList result = new RevertedDocList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (docItemBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            docItem_ = java.util.Collections.unmodifiableList(docItem_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.docItem_ = docItem_;
        } else {
          result.docItem_ = docItemBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RevertedDocList) {
          return mergeFrom((RevertedDocList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RevertedDocList other) {
        if (other == RevertedDocList.getDefaultInstance()) return this;
        if (docItemBuilder_ == null) {
          if (!other.docItem_.isEmpty()) {
            if (docItem_.isEmpty()) {
              docItem_ = other.docItem_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDocItemIsMutable();
              docItem_.addAll(other.docItem_);
            }
            onChanged();
          }
        } else {
          if (!other.docItem_.isEmpty()) {
            if (docItemBuilder_.isEmpty()) {
              docItemBuilder_.dispose();
              docItemBuilder_ = null;
              docItem_ = other.docItem_;
              bitField0_ = (bitField0_ & ~0x00000001);
              docItemBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDocItemFieldBuilder() : null;
            } else {
              docItemBuilder_.addAllMessages(other.docItem_);
            }
          }
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000002;
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        for (int i = 0; i < getDocItemCount(); i++) {
          if (!getDocItem(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RevertedDocList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RevertedDocList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<DocItem> docItem_ =
        java.util.Collections.emptyList();
      private void ensureDocItemIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          docItem_ = new java.util.ArrayList<DocItem>(docItem_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          DocItem, DocItem.Builder, DocItemOrBuilder> docItemBuilder_;

      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public java.util.List<DocItem> getDocItemList() {
        if (docItemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(docItem_);
        } else {
          return docItemBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public int getDocItemCount() {
        if (docItemBuilder_ == null) {
          return docItem_.size();
        } else {
          return docItemBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public DocItem getDocItem(int index) {
        if (docItemBuilder_ == null) {
          return docItem_.get(index);
        } else {
          return docItemBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public Builder setDocItem(
          int index, DocItem value) {
        if (docItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocItemIsMutable();
          docItem_.set(index, value);
          onChanged();
        } else {
          docItemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public Builder setDocItem(
          int index, DocItem.Builder builderForValue) {
        if (docItemBuilder_ == null) {
          ensureDocItemIsMutable();
          docItem_.set(index, builderForValue.build());
          onChanged();
        } else {
          docItemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public Builder addDocItem(DocItem value) {
        if (docItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocItemIsMutable();
          docItem_.add(value);
          onChanged();
        } else {
          docItemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public Builder addDocItem(
          int index, DocItem value) {
        if (docItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocItemIsMutable();
          docItem_.add(index, value);
          onChanged();
        } else {
          docItemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public Builder addDocItem(
          DocItem.Builder builderForValue) {
        if (docItemBuilder_ == null) {
          ensureDocItemIsMutable();
          docItem_.add(builderForValue.build());
          onChanged();
        } else {
          docItemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public Builder addDocItem(
          int index, DocItem.Builder builderForValue) {
        if (docItemBuilder_ == null) {
          ensureDocItemIsMutable();
          docItem_.add(index, builderForValue.build());
          onChanged();
        } else {
          docItemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public Builder addAllDocItem(
          Iterable<? extends DocItem> values) {
        if (docItemBuilder_ == null) {
          ensureDocItemIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, docItem_);
          onChanged();
        } else {
          docItemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public Builder clearDocItem() {
        if (docItemBuilder_ == null) {
          docItem_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          docItemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public Builder removeDocItem(int index) {
        if (docItemBuilder_ == null) {
          ensureDocItemIsMutable();
          docItem_.remove(index);
          onChanged();
        } else {
          docItemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public DocItem.Builder getDocItemBuilder(
          int index) {
        return getDocItemFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public DocItemOrBuilder getDocItemOrBuilder(
          int index) {
        if (docItemBuilder_ == null) {
          return docItem_.get(index);  } else {
          return docItemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public java.util.List<? extends DocItemOrBuilder>
           getDocItemOrBuilderList() {
        if (docItemBuilder_ != null) {
          return docItemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(docItem_);
        }
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public DocItem.Builder addDocItemBuilder() {
        return getDocItemFieldBuilder().addBuilder(
            DocItem.getDefaultInstance());
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public DocItem.Builder addDocItemBuilder(
          int index) {
        return getDocItemFieldBuilder().addBuilder(
            index, DocItem.getDefaultInstance());
      }
      /**
       * <code>repeated .RevertedDocList.DocItem docItem = 1;</code>
       */
      public java.util.List<DocItem.Builder>
           getDocItemBuilderList() {
        return getDocItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          DocItem, DocItem.Builder, DocItemOrBuilder>
          getDocItemFieldBuilder() {
        if (docItemBuilder_ == null) {
          docItemBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              DocItem, DocItem.Builder, DocItemOrBuilder>(
                  docItem_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          docItem_ = null;
        }
        return docItemBuilder_;
      }

      private Object type_ = "";
      /**
       * <code>required string type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string type = 2;</code>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RevertedDocList)
    }

    // @@protoc_insertion_point(class_scope:RevertedDocList)
    private static final RevertedDocList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RevertedDocList();
    }

    public static RevertedDocList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<RevertedDocList>
        PARSER = new com.google.protobuf.AbstractParser<RevertedDocList>() {
      @Override
      public RevertedDocList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RevertedDocList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RevertedDocList> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RevertedDocList> getParserForType() {
      return PARSER;
    }

    @Override
    public RevertedDocList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RevertedDocList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RevertedDocList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RevertedDocList_DocItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RevertedDocList_DocItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025RevertedDocList.proto\"\203\001\n\017RevertedDocL" +
      "ist\022)\n\007docItem\030\001 \003(\0132\030.RevertedDocList.D" +
      "ocItem\022\014\n\004type\030\002 \002(\t\0327\n\007DocItem\022\r\n\005docId" +
      "\030\001 \002(\t\022\r\n\005score\030\002 \001(\002\022\016\n\006reason\030\003 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RevertedDocList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RevertedDocList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RevertedDocList_descriptor,
        new String[] { "DocItem", "Type", });
    internal_static_RevertedDocList_DocItem_descriptor =
      internal_static_RevertedDocList_descriptor.getNestedTypes().get(0);
    internal_static_RevertedDocList_DocItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RevertedDocList_DocItem_descriptor,
        new String[] { "DocId", "Score", "Reason", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
